### ISSUE TITLE
Installation error on CentOs7.4

### ISSUE THREAD

**Issue by j209** [flectrahq/flectra#10]
[frappe@localhost ~]$ sudo yum install flectra_1.0.latest.noarch.rpm
[sudo] password for frappe: 
Loaded plugins: fastestmirror, langpacks
Examining flectra_1.0.latest.noarch.rpm: flectra-1.0-1.noarch
Marking flectra_1.0.latest.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package flectra.noarch 0:1.0-1 will be installed
--> Processing Dependency: babel for package: flectra-1.0-1.noarch
Loading mirror speeds from cached hostfile
 * base: mirror.steadfast.net
 * epel: ftp.cuhk.edu.hk
 * extras: mirror.steadfast.net
 * ius: mirror.its.dal.ca
 * updates: mirror.steadfast.net
--> Processing Dependency: libxslt-python for package: flectra-1.0-1.noarch
--> Processing Dependency: nodejs-less for package: flectra-1.0-1.noarch
--> Processing Dependency: pychart for package: flectra-1.0-1.noarch
--> Processing Dependency: pyparsing for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-PyPDF2 for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-PyYAML for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-babel for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-dateutil for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-decorator for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-docutils for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-feedparser for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-gevent for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-greenlet for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-html2text for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-jinja2 for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-lxml for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-mako for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-markupsafe for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-mock for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-num2words for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-ofxparse for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-passlib for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pillow for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-psutil for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-psycopg2 for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pydot for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pyldap for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pyparsing for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pyserial for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pytz for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pyusb for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-qrcode for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-reportlab for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-requests for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-six for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-stdnum for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-suds for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-vatnumber for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-vobject for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-werkzeug for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-xlrd for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-xlwt for package: flectra-1.0-1.noarch
--> Running transaction check
---> Package babel.noarch 0:0.9.6-8.el7 will be installed
--> Processing Dependency: python-babel for package: babel-0.9.6-8.el7.noarch
---> Package flectra.noarch 0:1.0-1 will be installed
--> Processing Dependency: python3-PyPDF2 for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-PyYAML for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-babel for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-dateutil for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-decorator for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-docutils for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-feedparser for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-gevent for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-greenlet for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-html2text for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-jinja2 for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-lxml for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-mako for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-markupsafe for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-mock for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-num2words for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-ofxparse for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-passlib for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pillow for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-psutil for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-psycopg2 for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pydot for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pyldap for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pyparsing for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pyserial for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pytz for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pyusb for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-qrcode for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-reportlab for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-requests for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-six for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-stdnum for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-suds for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-vatnumber for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-vobject for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-werkzeug for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-xlrd for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-xlwt for package: flectra-1.0-1.noarch
---> Package libxslt-python.x86_64 0:1.1.28-5.el7 will be installed
---> Package nodejs-less.noarch 0:1.7.0-2.el7 will be installed
--> Processing Dependency: npm(ycssmin) < 1.1 for package: nodejs-less-1.7.0-2.el7.noarch
--> Processing Dependency: npm(ycssmin) >= 1.0.1 for package: nodejs-less-1.7.0-2.el7.noarch
---> Package pychart.noarch 0:1.39-17.el7 will be installed
---> Package pyparsing.noarch 0:1.5.6-9.el7 will be installed
--> Running transaction check
---> Package flectra.noarch 0:1.0-1 will be installed
--> Processing Dependency: python3-PyPDF2 for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-PyYAML for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-babel for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-dateutil for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-decorator for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-docutils for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-feedparser for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-gevent for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-greenlet for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-html2text for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-jinja2 for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-lxml for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-mako for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-markupsafe for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-mock for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-num2words for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-ofxparse for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-passlib for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pillow for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-psutil for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-psycopg2 for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pydot for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pyldap for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pyparsing for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pyserial for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pytz for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-pyusb for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-qrcode for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-reportlab for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-requests for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-six for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-stdnum for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-suds for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-vatnumber for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-vobject for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-werkzeug for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-xlrd for package: flectra-1.0-1.noarch
--> Processing Dependency: python3-xlwt for package: flectra-1.0-1.noarch
---> Package python-babel.noarch 0:0.9.6-8.el7 will be installed
---> Package ycssmin.noarch 0:1.0.1-6.el7 will be installed
--> Finished Dependency Resolution
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-qrcode
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-reportlab
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-stdnum
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-greenlet
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-PyYAML
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-pytz
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-num2words
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-markupsafe
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-mako
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-pyusb
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-ofxparse
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-feedparser
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-decorator
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-werkzeug
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-pyldap
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-gevent
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-pyserial
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-xlrd
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-psutil
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-PyPDF2
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-docutils
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-passlib
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-babel
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-mock
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-dateutil
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-pydot
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-requests
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-vatnumber
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-pyparsing
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-psycopg2
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-lxml
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-xlwt
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-vobject
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-six
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-pillow
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-suds
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-jinja2
Error: Package: flectra-1.0-1.noarch (/flectra_1.0.latest.noarch)
           Requires: python3-html2text
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[frappe@localhost ~]$

**Comment by thomich** [comment]
Hello

Thanks for report.
One way dependencies are loaded other way broken.
Please try install some dependencies manually and install Flectra again and check whats happen with manual installed dependencies.

Thanks for your response.

**Comment by flectrahqadmin** [comment]
you may follow this : https://gist.github.com/flectrahqadmin/d4c827577b3251a9505d3b697b1068be#gistcomment-2304635
