### ISSUE TITLE
Why does the alpha release do not include the functionalities shown in the website and videos ?

### ISSUE THREAD

**Issue by slimit** [flectrahq/flectra#11]
Impacted versions: alpha1.0

Steps to reproduce: install current version (branch master commit [2c0fd80](https://github.com/flectrahq/flectra/commit/2c0fd80734f1a899905f7274143b8fb925bde0dd)

Current behavior: Odoo 11 CE functionalities with Flectra rebranding

Expected behavior: Flectra improvements described in the website [Alpha release announcement] (https://flectrahq.com/page/alpha-release-announcements)

Video/Screenshot link (optional):

Does the alpha release stands just as a first commit for the project fork ? And FlectraHQ work is not yet published ?

**Comment by zilvinui** [comment]
flectra team working on functionality to bring it one by one. as they have said all functionality is developed but not commited to repository. maybe they migrating code form v10 to v11 or something..

**Comment by slimit** [comment]
Can you please share where they have said that all functionality is developed but not commited to repository ?

**Comment by zilvinui** [comment]
https://gitter.im/flectrahq-erp/Lobby

**Comment by thomich** [comment]
@slimit Thanks for your information
We are hard working on all the parts to bring PR's soon.

Follow as in our Lobby as @zilvinui has suggested.

**Comment by parthivgls** [comment]
@slimit features are mentioned here https://flectrahq.com/page/alpha-release-announcements
