### ISSUE TITLE
Contract Management

### ISSUE THREAD

**Issue by flectrahqadmin** [flectrahq/flectra#14]

**Comment by wpichler** [comment]
Do you need any help on this issue ? I do have a good contract management for odoo v10. I could contribute this to the project...

**Comment by parthivgls** [comment]
@wpichler we are already in middle of migrating old v8 contract management to flectra. We can for sure look into your module to create more feature and betterment.

**Comment by parthivgls** [comment]
Done with https://github.com/flectrahq/flectra/pull/56
