### ISSUE TITLE
db selector, manager issue

### ISSUE THREAD

**Issue by zilvinui** [flectrahq/flectra#16]
Impacted versions:
master
Steps to reproduce:
go to database manager
Current behavior:
wont load .css, .js files
Expected behavior:
loaded css
Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/12909126/31500188-7286019e-af6f-11e7-8bcd-4150dabc93f3.png)

errors on dev tools
![image](https://user-images.githubusercontent.com/12909126/31500245-95cb1cfc-af6f-11e7-953b-e2fddc732064.png)

**Comment by bud-e** [comment]
Hello, @zilvinui ,

I'm unable to reproduce this error in my local machine.
So, can you please provide steps to reproduce the same.

Can you test it again with latest update of master?

---
Thanks.

**Comment by zilvinui** [comment]
hello,
i will try install everything freshly on other server and when update everything. something strange was happening yesterday, i always clear all browsing data, use incognito mode, but all css, js messed.. maybe its due nginx proxy, i compress all css, js and so on.. same server was previously used for odoo11.. i will update..

**Comment by Vladlenb** [comment]
try  
npm install -g less
npm install -g less-plugin-clean-css
ln -s /usr/local/bin/lessc /usr/bin/lessc

**Comment by zilvinui** [comment]
i confirm that this issue was due server configuration (caching some stuff). on fresh install everything runs ok.
