### ISSUE TITLE
New UI design

### ISSUE THREAD

**Issue by flectrahqadmin** [flectrahq/flectra#19]
New UI design with capability of changing Fonts and Color as per user configuration.

**Comment by parthivgls** [comment]
https://github.com/flectrahq/flectra/pull/45

**Comment by sb-flectra** [comment]
Merged with commit ref. ca2a2f2d5fbb1c0c66499e310176ad7f889bd2c1 & c3f31a892d30d4feaeb714dd987d169f823aa66d
