### ISSUE TITLE
Payment Followup Module

### ISSUE THREAD

**Issue by flectrahqadmin** [flectrahq/flectra#2]

**Comment by thomich** [comment]
#47

**Comment by thomich** [comment]
My Review:
. Configuration, Followup Levels: where to show levels, if changing them
. Open Manual Followups: open fups instead of partner form
. Followup eMail: more beautiful table of lines

**Comment by sb-flectra** [comment]
Closing this issue, As we've PR for this issue.
So all the conversation will be placed in one place, In PR: https://github.com/flectrahq/flectra/pull/47
