### ISSUE TITLE
Erro: REST API Module

### ISSUE THREAD

**Issue by argitx** [flectrahq/flectra#20]
Impacted versions:
Flectra v1.0
Steps to reproduce:
Running Flectra from the console and when installing REST API Module following error is showing:

2017-12-26 08:40:04,961 20719 ERROR flectra_d02c flectra.addons.rest_api.controllers.main: ERROR: To proper setup OAuth - it's necessary to set the parameter 'db_name' in flectra config file!

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by kaushal-flectra** [comment]
@argitx provide more information or step to reproduce issues

**Comment by sb-flectra** [comment]
Hi @argitx, 

Thanks for reporting this one. As for the REST API you've to specify DB name.

When you run flectra server without specifying any DB. Then this error occur. But when you start the flectra server with specific DB name then this error is not occur.

Error message: https://github.com/flectrahq/flectra/blob/1.0/addons/rest_api/controllers/main.py#L365

As REST is only available to specific DB. Not all the DB which are available with REST API installed.
So, It is necessary to specify DB name when restart the flectra server (`-d parameter is necessary`).
`./flectra-bin --addons=addons -d 'specific DB name'`

Though showing error is not appropriate!! We already convert this error to warning!

Thanks.
