### ISSUE TITLE
Why fork?

### ISSUE THREAD

**Issue by littlepea** [flectrahq/flectra#20]
Hello,

I'm just curious, why did you decide to fork Odoo? What are you trying to achieve that Odoo couldn't provide?

Thanks.

**Comment by flectrahqadmin** [comment]
Short Answer : Odoo is moving lot of important module to Odoo Enterprise only.. and in same way the increase the prices for Odoo Enterprise up to 50-100%... Back question, why should we not?

More details : https://flectrahq.com/page/aboutus

**Comment by littlepea** [comment]
That's clear, thanks!
No reason why you should not.
