### ISSUE TITLE
Accounting and Payroll Still Missing

### ISSUE THREAD

**Issue by knimer** [flectrahq/flectra#21]
Impacted versions: Flectra 1.0alpha CE

Steps to reproduce: Just search for the Pyroll and Accounting apps. They are still missing

Current behavior: 

Expected behavior:

Video/Screenshot link (optional):

**Comment by thomich** [comment]
Hello @knimer 
Thanks for your input.

Please check Flectra 1.0 Alpha announcement about upcoming Apps in progress:
https://flectrahq.com/page/alpha-release-announcements

For Payroll there is a default App available (hr_payroll):
![selection_013](https://user-images.githubusercontent.com/4398840/31582629-36edd726-b189-11e7-9f15-a7155ea07e8c.png)
