### ISSUE TITLE
POS Showing Odoo Logo

### ISSUE THREAD

**Issue by mobarmeg** [flectrahq/flectra#24]
**Impacted versions:** 1.0

**Steps to reproduce:** Install POS module then open a new POS session

**Current behavior:** POS screen is showing with Odoo logo

**Expected behavior:** It should show and reflects Flectra's style

**Comment by argitx** [comment]
found Odoo logo in this file /addons/point_of_sale/static/src/img/logo.png

**Comment by kaushal-flectra** [comment]
Already Fixed in Commit: https://github.com/flectrahq/flectra/pull/23/commits/c40cbc7ce5f3b09b4601482701fd1a4c2ea5e196
