### ISSUE TITLE
No tax after reboot

### ISSUE THREAD

**Issue by Arturo2511** [flectrahq/flectra#29]
No tax after reboot server.
Application: Belgium - Payroll with Accounting
Impacted versions: 1.00

Steps to reproduce: Reboot server

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by thomich** [comment]
Hello @Arturo2511 

Thanks for report.
What kind of installation you did? From source or binary?

Thanks for response.
thomi

**Comment by kaushal-flectra** [comment]
@Arturo2511 unable to reproduce this issue with the latest code `master` or `1.0`.
So, need more information to reproduce it.

**Comment by Arturo2511** [comment]
Hello, this happens with the .deb and sources.
I installed the VAT application of Belgium. After a reboot of the server, all taxes disappeared. This is produced after the installation of the "Sales" module. If I delete it, taxes do not come back.
![capture d ecran 2017-12-28 a 15 42 21](https://user-images.githubusercontent.com/7384516/34413773-c1f94c9c-ebe5-11e7-9fec-e727ba7bef21.png)

**Comment by sb-flectra** [comment]
Dear @Arturo2511 

As I'm unable to reproduce your issue, as you said I followed all the steps, installing all the mention modules/apps but still after rebooting the server, all taxes are still there!!

Yes, but if you deleted those taxes, manually. Then obviously it'll deleted from your DB & it'll not display in Taxes menu, even after rebooting the server.

Thanks.
