### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by manishmarahatta** [flectrahq/flectra#3]
<img width="1440" alt="screen shot 2017-10-08 at 11 39 27 am" src="https://user-images.githubusercontent.com/13973154/31314308-9092931e-ac1d-11e7-920d-b1be7f547dbb.png">
Command "/Users/manishmarahatta/flectra/venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/tl/xrbs4m0535g_g3qtp101jw4c0000gn/T/pip-build-ufey9cl7/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/tl/xrbs4m0535g_g3qtp101jw4c0000gn/T/pip-mr6r94sf-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/manishmarahatta/flectra/venv/bin/../include/site/python3.6/lxml" failed with error code 1 in /private/var/folders/tl/xrbs4m0535g_g3qtp101jw4c0000gn/T/pip-build-ufey9cl7/lxml/

**Comment by diwap** [comment]
I'm facing the same problem

Command "/home/diwap/flectra/venv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6lmc3j5y/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mzbrq6wv-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/diwap/flectra/venv/include/site/python3.5/lxml" failed with error code 1 in /tmp/pip-build-6lmc3j5y/lxml/

**Comment by thomich** [comment]
@manishmarahatta @diwap Thanks for reporting.
Please add steps to reproduce and best ist to follow our issue steps ;)

**************************
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**************************

Thanks
thomi

**Comment by phoenixsampras** [comment]
Please provide STEP by STEP installation guide. Devs are interested to test in order to dev or migrate apps from ODOO.

**Comment by parthivgls** [comment]
@manishmarahatta @phoenixsampras please follow this gist https://gist.github.com/flectrahqadmin/d4c827577b3251a9505d3b697b1068be
