### ISSUE TITLE
Links to get modules and themes aren't working (yet ?)

### ISSUE THREAD

**Issue by deajan** [flectrahq/flectra#30]
Impacted versions: 1.0

Steps to reproduce: Goto dashboard > Applications > App store (or themes)

Current behavior: Goes to https://www.flectrahq.com/apps/modules which isn't working

Expected behavior: Should go to https://flectrahq.com/apps/modules ?

Video/Screenshot link (optional):

**Comment by parthivgls** [comment]
We are yet to bring our own app store live. :)
