### ISSUE TITLE
Migration from ODOO

### ISSUE THREAD

**Issue by zuher83** [flectrahq/flectra#31]
Hi,
Have you considered the possibility of an existing database migration from ODOO to FLECTRA

Thanks

**Comment by thomich** [comment]
Hey @zuher83 

Checkout our FAQ, special the part:
https://flectrahq.com/page/aboutus

We will provide base scripts for migration from Odoo to Flectra..
Details will follow.

Regards
Thomas

**Comment by zuher83** [comment]
thank you for your reply @thomich
