### ISSUE TITLE
Failed To Update View server when a new field is added to the notebook component

### ISSUE THREAD

**Issue by niulinlnc** [flectrahq/flectra#35]
Impacted versions:
flectra v1.0
Steps to reproduce:
1.build or edit a app
2.add a notebook component
3.add a new field to the notebook component
![2](https://user-images.githubusercontent.com/11767049/34372479-0c5f2c24-eb10-11e7-96a0-8d490f9a21d0.jpg)

**Comment by Jungi-Flectra** [comment]
@niulinlnc The issue has been fixed please take pull of latest commit and check the same with latest code.thank you.
