### ISSUE TITLE
Failed to upgrade from Beta version (Database structure integrity)

### ISSUE THREAD

**Issue by hafedh-trimeche** [flectrahq/flectra#37]
Impacted versions: 1.0

Steps to reproduce:

Current behavior: Database integrity problem

Expected behavior: Dynamically update database structure 

Video/Screenshot link (optional):

**[Flectra.Txt](https://github.com/flectrahq/flectra/files/1588775/Flectra.Txt)**

Missed or modified fields should be handled to meet the new release (Alpha --> Beta  --> Release)

**Comment by sb-flectra** [comment]
It's not possible to maintain database integrity  for `alpha -> beta -> release`
DB integrity can possible with `stable release -> stable release`
