### ISSUE TITLE
Uncaught ReferenceError: ace is not defined

### ISSUE THREAD

**Issue by okkype** [flectrahq/flectra#4]
get "Uncaught ReferenceError: ace is not defined" when edit view (debug mode)

Screenshot:
![screencapture-localhost-7073-web-1507475773609](https://user-images.githubusercontent.com/15972773/31318094-b52ac21a-ac76-11e7-98c8-bea0a2aa4df3.png)

**Comment by bud-e** [comment]
Thanks for Reporting.

Its fixed with commit reference https://github.com/flectrahq/flectra/commit/4738668f477d5f895bbb66cd8cf079f3ddc32099
