### ISSUE TITLE
Failed To Update View server when a new field[monetary or select] is added to the form

### ISSUE THREAD

**Issue by niulinlnc** [flectrahq/flectra#40]
Impacted versions:
flectra v1.0
Steps to reproduce:
1.build a new app
2.views>form>add a new field [monetary or select]
![default](https://user-images.githubusercontent.com/11767049/34383778-bc083c96-eb52-11e7-9392-8b895e18f39f.png)

**Comment by niulinlnc** [comment]
@Jungi-Flectra 
After the update, add the monetary field appears such a hint:
You cannot drop this field on[self.model] model.
![default](https://user-images.githubusercontent.com/11767049/34412774-295995fc-ec1a-11e7-96c0-94b05e8ca60a.jpg)

**Comment by niulinlnc** [comment]
Add another questions:
The downside of app builder is that every time you add a new field, The current editing form will be a serious jitter refresh. Odoo studio no such problem.

**Comment by Jungi-Flectra** [comment]
Yes the dialog pops up because The reason for monetary field raises exception is we have to find currency_id on the current model : a monetary field can not be added if such a field does not exist on the model.
