### ISSUE TITLE
Call Rest API error : No access token was provided in request header!

### ISSUE THREAD

**Issue by ichan-mb** [flectrahq/flectra#44]
Impacted versions:
Flectra v1.0
Steps to reproduce:
first of all call url POST to api/auth/get_tokens to get token API, and then use that token on header when i call /api/project.task
Current behavior:
give me an json response with content : 
`{
    "error_descrip": "No access token was provided in request header!",
    "error": "no_access_token"
}`
Expected behavior:
return json data of project.task
Video/Screenshot link (optional):

**Comment by kaushal-flectra** [comment]
@ichan-mb You need pass access_token with request header while any option with model data.

Refer:- https://github.com/flectrahq/flectra/blob/1.0/addons/rest_api/readme.md
