### ISSUE TITLE
Enterprise References & Follow Up Module

### ISSUE THREAD

**Issue by Ives86** [flectrahq/flectra#45]
Impacted versions:
Flectra v1.0

Steps to reproduce:
Go to Settings

Current behavior:

Enterprise is referenced next to some of the options.  When selecting the options, they flag up an error saying module not available. 

Likewise, selecting follow up module, throws up an Enterprise related error.

Expected behavior:

Should the Enterprise reference be there?  Should the options be available at all?

Should the follow up module install or not be there again?  Follow ups were part of the information on the website as available functionality.

Video/Screenshot link (optional):

**Comment by sb-flectra** [comment]
@Ives86 
Have you check with updated code?
As this issue is not anymore exists!!

Thanks.
