### ISSUE TITLE
PLM Category won't allow me assign approval and validator person field.

### ISSUE THREAD

**Issue by vinay-vperfect** [flectrahq/flectra#49]
Impacted versions:1.0

Steps to reproduce:Open Category in form view and assigned team but team could not visualize any fields related to that. As main form show fields with readonly so this should related field with ref of above team assignment.

Current behavior: Due to not assign value facing related programming constraint for assigning approval and validator.

Expected behavior: It should allow me as access rights already assigned to related user.

Video/Screenshot link (optional):
![screen shot 2017-12-29 at 12 00 22 pm](https://user-images.githubusercontent.com/7600272/34431206-232ed4ac-ec93-11e7-8427-8107f6301d02.png)
![screen shot 2017-12-29 at 12 19 15 pm](https://user-images.githubusercontent.com/7600272/34431207-23660f44-ec93-11e7-8e23-88540577d19e.png)
![screen shot 2017-12-29 at 12 19 37 pm](https://user-images.githubusercontent.com/7600272/34431208-239acf18-ec93-11e7-8c4c-b7f85fe0b5d4.png)

**Comment by dipesh-suthar-flectra** [comment]
Hello @vinay-vperfect 

Thank you for reaching out, I really appreciate you taking the time to share ideas. 
I can see you have given rights to admin user and admin user should be allow to have all the access of system. 

Surely our team will improve it and we will update it soon with fix. 
Keep calm & continue testing ;)
