### ISSUE TITLE
 New Design of flectra for Backend

### ISSUE THREAD

**Issue by malatestay** [flectrahq/flectra#52]
Impacted versions: master

Steps to reproduce: last upgrade

Current behavior:

After updating flectra from New Design of flectra for Backend, all the backend has disappeared, no more menu no icons.
Is there something we can do?

Expected behavior:
find access to the backend

Video/Screenshot link (optional):
see doc joined
[Doc1.pdf](https://github.com/flectrahq/flectra/files/1507443/Doc1.pdf)

**Comment by thomich** [comment]
Hello @malatestay 

Thanks for your report.
We recommend to use new db and not use Flectra in production area, cause we are still Alpha.

Thanks for your understanding

**Comment by malatestay** [comment]
Hello @thomich
Thank fro answers.
Today i use only on test and evaluate.
Regards Yves
