### ISSUE TITLE
crm excel template messy code, same problem with product excel template

### ISSUE THREAD

**Issue by sotsam** [flectrahq/flectra#54]
Impacted versions:flectra 1.0

Steps to reproduce:settings-implementation-crm-download excel template

Current behavior:excel template messy code

Expected behavior:no messy code

Video/Screenshot link (optional):

**Comment by sotsam** [comment]
![image](https://user-images.githubusercontent.com/28956124/34438152-962d6882-ecdf-11e7-9e9d-29fc558bcc73.png)

**Comment by sotsam** [comment]
![image](https://user-images.githubusercontent.com/28956124/34438167-bda0337c-ecdf-11e7-8844-fbeb64a64396.png)

**Comment by sotsam** [comment]
same ubuntu system, odoo excel templates are ok

**Comment by slimit** [comment]
Will test it.
