### ISSUE TITLE
Website Module Langage Bug

### ISSUE THREAD

**Issue by Arturo2511** [flectrahq/flectra#65]
Impacted versions: 1.0

Steps to reproduce: Install Website Module after choice french langage.

The langage after install website module is english.
If I remove website module, the langage is always english and impossible to switch in french.

**Comment by pratik-flectra** [comment]
Hello @Arturo2511 

Can you please check it again with the latest update of code (Commit No.: f47a627) with new DB. As I'm not able to reproduce it!!
If it still exists then feel free to re-open the issue.

Thanks.
