### ISSUE TITLE
Database Manager Still Using Odoo Logo

### ISSUE THREAD

**Issue by okkype** [flectrahq/flectra#8]
Impacted versions:
1.0 alpha

Steps to reproduce:

Current behavior:
Database Manager Still Using Odoo Logo

Expected behavior:
Database Manager Using Flectra Logo, we propose web_debranding (or assoc) as base module

Video/Screenshot link (optional):
![screencapture-localhost-7073-web-database-manager-1507598847548](https://user-images.githubusercontent.com/15972773/31365495-a4ba2c98-ad95-11e7-9aaf-198b69f44954.png)

**Comment by bud-e** [comment]
Fixed with b34a7ed4ebc49e5b76405e473b57c45fc95b0fcf
