### ISSUE TITLE
ImportError: No module named 'PyPDF2' on Python 2.7

### ISSUE THREAD

**Issue by okkype** [flectrahq/flectra#9]
Impacted versions:
1.0 alpha

Steps to reproduce:

Current behavior:
on python 2.7, ImportError: No module named 'PyPDF2' but run normal on python 3
is flectra run only on python 3? if true, you can close this issue

Expected behavior:

Video/Screenshot link (optional):
![cuplikan layar dari 2017-10-10 09-35-20](https://user-images.githubusercontent.com/15972773/31366991-82f5a25a-ad9e-11e7-92a3-1cfa87d34f56.png)

**Comment by bud-e** [comment]
Yes, Its `Py3` & In order to successful run you need to install that `PyPDF2` module.
